port: "8080"

db:
#  username: "xqvroszblcatgl"
#  host: "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com"
#  port: "5432"
#  dbname: "dq8uqaagtkjv4"
#  sslmode: "require"
#  password: "103bc1cd7154ea19a5966ca8e1d3db8f44a78634ca3049770b9d47dc1e3fdc02"
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "emulator"
  sslmode: "disable"
  password: "password"